-- RESET ALL TABLE, TRIGGER AND SEQUENCE CMS SURVEY
-- DROP ALL TABLES CMS SURVEY
DROP TABLE CMS_SURVEY;

DROP TABLE CMS_QUESTIONS_GROUP;

DROP TABLE CMS_QUESTIONS;

DROP TABLE CMS_ANSWERS_GROUP;

DROP TABLE CMS_ANSWERS;

DROP TABLE CMS_USERS;

DROP TABLE CMS_USERS_ROLES;

DROP TABLE CMS_USERS_ROLES_GROUP;

DROP TABLE CMS_AUDIT_TRAIL;

DROP TABLE CMS_LOG_HISTORY_USER;

-- DROP ALL SEQUENCES
DROP SEQUENCE CMS_SURVEY_SEQ;

DROP SEQUENCE CMS_QUESTIONS_GROUP_SEQ;

DROP SEQUENCE CMS_QUESTIONS_SEQ;

DROP SEQUENCE CMS_ANSWERS_SEQ;

DROP SEQUENCE CMS_USERS_SEQ;

DROP SEQUENCE CMS_USERS_ROLES_SEQ;

DROP SEQUENCE CMS_USERS_ROLES_GROUP_SEQ;

DROP SEQUENCE CMS_AUDIT_TRAIL_SEQ;

DROP SEQUENCE CMS_LOG_HISTORY_USER_SEQ;

-- DROP ALL TRIGGERS
DROP TRIGGER CMS_SURVEY_TRG;

DROP TRIGGER CMS_QUESTIONS_GROUP_TRG;

DROP TRIGGER CMS_QUESTIONS_TRG;

DROP TRIGGER CMS_ANSWERS_TRG;

DROP TRIGGER CMS_USERS_TRG;

DROP TRIGGER CMS_USERS_ROLES_TRG;

DROP TRIGGER CMS_USERS_ROLES_GROUP_TRG;

DROP TRIGGER CMS_AUDIT_TRAIL_TRG;

DROP TRIGGER CMS_LOG_HISTORY_USER_TRG;