--------------------------------------------------------
--  DDL for Trigger CMS_ANSWERS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CMS_ANSWERS_TRG" 
BEFORE INSERT ON CMS_ANSWERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ANSWER_CODE IS NULL THEN
      SELECT CMS_ANSWERS_SEQ.NEXTVAL INTO :NEW.ANSWER_CODE FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "CMS_ANSWERS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CMS_AUDIT_TRAIL_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CMS_AUDIT_TRAIL_TRG" 
BEFORE INSERT ON CMS_AUDIT_TRAIL 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.AUDIT_TRAIL_CODE IS NULL THEN
      SELECT CMS_AUDIT_TRAIL_SEQ.NEXTVAL INTO :NEW.AUDIT_TRAIL_CODE FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "CMS_AUDIT_TRAIL_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CMS_LOG_HISTORY_USER_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CMS_LOG_HISTORY_USER_TRG" 
BEFORE INSERT ON CMS_LOG_HISTORY_USER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT CMS_LOG_HISTORY_USER_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "CMS_LOG_HISTORY_USER_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CMS_QUESTIONS_GROUP_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CMS_QUESTIONS_GROUP_TRG" 
BEFORE INSERT ON CMS_QUESTIONS_GROUP 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT CMS_QUESTIONS_GROUP_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "CMS_QUESTIONS_GROUP_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CMS_QUESTIONS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CMS_QUESTIONS_TRG" 
BEFORE INSERT ON CMS_QUESTIONS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.QUESTION_CODE IS NULL THEN
      SELECT CMS_QUESTIONS_SEQ.NEXTVAL INTO :NEW.QUESTION_CODE FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "CMS_QUESTIONS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CMS_SURVEY_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CMS_SURVEY_TRG" 
BEFORE INSERT ON CMS_SURVEY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.SURVEY_CODE IS NULL THEN
      SELECT CMS_SURVEY_SEQ.NEXTVAL INTO :NEW.SURVEY_CODE FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "CMS_SURVEY_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CMS_USERS_ROLES_GROUP_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CMS_USERS_ROLES_GROUP_TRG" 
BEFORE INSERT ON CMS_USERS_ROLES_GROUP 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT CMS_USERS_ROLES_GROUP_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "CMS_USERS_ROLES_GROUP_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CMS_USERS_ROLES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CMS_USERS_ROLES_TRG" 
BEFORE INSERT ON CMS_USERS_ROLES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT CMS_USERS_ROLES_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "CMS_USERS_ROLES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CMS_USERS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CMS_USERS_TRG" 
BEFORE INSERT ON CMS_USERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT CMS_USERS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "CMS_USERS_TRG" ENABLE;
